[pytest]
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning
    ignore::starlette.exceptions.StarletteDeprecationWarning
    ignore:The anyio\.abc\.BlockingPortal alias is deprecated:DeprecationWarning
    ignore:Using `httpx` with `starlette\.testclient` is deprecated:starlette.exceptions.StarletteDeprecationWarning
