/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        serif: [
          '"Newsreader"',
          "ui-serif",
          "Georgia",
          "Cambria",
          '"Times New Roman"',
          "serif",
        ],
        sans: [
          '"Plus Jakarta Sans"',
          '"SF Pro Display"',
          '"SF Pro Text"',
          "-apple-system",
          "BlinkMacSystemFont",
          '"Inter"',
          "system-ui",
          '"Segoe UI"',
          "Roboto",
          "sans-serif",
        ],
        mono: [
          '"JetBrains Mono"',
          '"SF Mono"',
          "ui-monospace",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
      },
      letterSpacing: {
        "apple-tightest": "-0.035em",
        "apple-tighter": "-0.028em",
        "apple-tight": "-0.02em",
        "apple-headline": "-0.015em",
        "apple-body": "-0.006em",
        "apple-caps": "0.06em",
        "perplexity-title": "-0.025em",
      },
      colors: {
        cream: "#FAF9F5",
        canvas: "#FAF9F5",
        card: "#FFFFFF",
        navy: "#18181B",
        ink: "#171715",
        muted: "#6B6A66",
        green: "#059669",
        warn: "#DC2626",
        line: "rgba(23, 23, 21, 0.07)",
        claude: {
          canvas: "#FAF9F5",
          stone: "#F4F3ED",
          border: "#E6E4DD",
          charcoal: "#171715",
          muted: "#73726C",
          terracotta: "#C96442",
          sand: "#EDECE6",
        },
        perplexity: {
          teal: "#009E90",
          "teal-light": "#E6F7F5",
          dark: "#191A1A",
          border: "rgba(25, 26, 26, 0.08)",
          card: "rgba(255, 255, 255, 0.85)",
        },
      },
      boxShadow: {
        claude: "0 2px 12px -2px rgba(23, 23, 21, 0.04), 0 1px 3px rgba(23, 23, 21, 0.02)",
        "claude-hover": "0 8px 30px -4px rgba(23, 23, 21, 0.08), 0 2px 8px -2px rgba(23, 23, 21, 0.03)",
        perplexity: "0 1px 3px rgba(0, 0, 0, 0.04), 0 6px 24px -4px rgba(0, 0, 0, 0.04)",
      },
    },
  },
  plugins: [],
};
