/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          '"SF Pro Display"',
          '"SF Pro Text"',
          "-apple-system",
          "BlinkMacSystemFont",
          '"Inter"',
          "system-ui",
          '"Segoe UI"',
          "Roboto",
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        mono: [
          '"SF Mono"',
          "ui-monospace",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
      },
      letterSpacing: {
        "apple-tightest": "-0.035em",
        "apple-tighter": "-0.028em",
        "apple-tight": "-0.02em",
        "apple-headline": "-0.015em",
        "apple-body": "-0.006em",
        "apple-caps": "0.06em",
      },
      fontSize: {
        "2xs": ["0.6875rem", { lineHeight: "0.9rem" }],
        "apple-caption-2": ["0.6875rem", { lineHeight: "0.8125rem", letterSpacing: "0.02em" }],
        "apple-caption-1": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0em" }],
        "apple-footnote": ["0.8125rem", { lineHeight: "1.125rem", letterSpacing: "-0.005em" }],
        "apple-subhead": ["0.9375rem", { lineHeight: "1.25rem", letterSpacing: "-0.01em" }],
        "apple-body": ["1.0625rem", { lineHeight: "1.375rem", letterSpacing: "-0.012em" }],
        "apple-headline": ["1.0625rem", { lineHeight: "1.375rem", letterSpacing: "-0.015em" }],
        "apple-title-3": ["1.25rem", { lineHeight: "1.5625rem", letterSpacing: "-0.018em" }],
        "apple-title-2": ["1.375rem", { lineHeight: "1.75rem", letterSpacing: "-0.022em" }],
        "apple-title-1": ["1.75rem", { lineHeight: "2.125rem", letterSpacing: "-0.026em" }],
        "apple-large-title": ["2.125rem", { lineHeight: "2.5625rem", letterSpacing: "-0.032em" }],
      },
      colors: {
        cream: "#F6F8FD",
        card: "#FFFFFF",
        navy: "#0F172A",
        green: "#059669",
        ink: "#0F172A",
        muted: "#64748B",
        warn: "#DC2626",
        line: "rgba(0, 0, 0, 0.06)",
        "apple-gray": {
          50: "#FBFBFD",
          100: "#F5F5F7",
          200: "#E8E8ED",
          300: "#D2D2D7",
          400: "#86868B",
          500: "#6E6E73",
          600: "#424245",
          700: "#1D1D1F",
        },
      },
    },
  },
  plugins: [],
};
